# Generated by Django 2.2 on 2019-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, upload_to='elements/'),
        ),
    ]
