# Generated by Django 2.2 on 2019-04-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expenses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='image',
        ),
    ]
